### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by rossjones** [datagovuk/publish_data#4]
Need to complete the dashboard and include "Harvesters" on the left hand-side (pointing to /harvest/list).

**Comment by rossjones** [comment]
The 'Manage Team' link should point at /team

**Comment by maria-izquierdo** [comment]
@maxf could you please review the code and fix the table on 'tasks' so it shows the status:
![screen shot 2016-10-12 at 18 06 42](https://cloud.githubusercontent.com/assets/17740822/19321574/7ff50c94-90ad-11e6-9a86-4331521b0c69.png)

and in the most popular section the arrows are aligned

thanks!
