### ISSUE TITLE
Manage team members

### ISSUE THREAD

**Issue by maria-izquierdo** [datagovuk/publish_data#48]
This is how Notify does it. I think we could do the same.

**Invite team members** 
![screen shot 2016-10-14 at 00 36 16](https://cloud.githubusercontent.com/assets/17740822/19370863/909c64bc-91a6-11e6-8932-f32cec43a903.png)

**See your permissions** 
![screen shot 2016-10-14 at 00 36 36](https://cloud.githubusercontent.com/assets/17740822/19370870/9fdcbc10-91a6-11e6-886e-49664e57145d.png)

**Comment by rossjones** [comment]
Sounds good. Should be easy to change, but ... how do we edit and remove users?
