### ISSUE TITLE
Back button 

### ISSUE THREAD

**Issue by maria-izquierdo** [datagovuk/publish_data#49]
In case we want to add a back button, here is the code:
https://gist.github.com/edwardhorsford/d8d3b206fc074aac86c3

and in register to vote, they have these steps. Could be interesting to test how it works with the publisher flow:
![screen shot 2016-10-14 at 00 13 36](https://cloud.githubusercontent.com/assets/17740822/19381148/405ede8e-91f2-11e6-906c-4f40906f8dd3.png)

**Comment by rossjones** [comment]
@maxf Seeing as this is a prototype, and we're controlling how this is tested, can we just use 

``` javascript
window.history.go(-1);
```

to do this?  So that we don't have to keep track of where we are in each template?

Also, I guess we need to decide where abouts on the page is should go?  To the left of the next button?  Below it?

**Comment by maxf** [comment]
Should be ok. We'll probably want to make it better after the prototype,
with field values remembered, etc.

**Comment by rossjones** [comment]
I've split this ticket to the "question x of y" is in https://github.com/datagovuk/publish_data/issues/56
