### ISSUE TITLE
Dataset list

### ISSUE THREAD

**Issue by rossjones** [datagovuk/publish_data#8]
Related to the dashboard, we were going to have a list of datasets from where the user can publish and/or schedule to publish.

**Comment by maxf** [comment]
- JS for filtering

**Comment by maxf** [comment]
![screenshot from 2016-10-06 12-01-16](https://cloud.githubusercontent.com/assets/69542/19150024/ae9d1960-8bbc-11e6-85fc-2a2fe01d8ed0.png)
